from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from server import views  # import from project folder

urlpatterns = [
    path('District/', views.District),
    path('DistrictDelete/<int:district_id>/', views.DistrictDelete),
    path('Admin/', views.Admin),
    path('AdminDelete/<int:admin_id>/', views.AdminDelete),
    path('Place/', views.Place),
    path('PlaceDelete/<int:place_id>/', views.PlaceDelete),
    path('bhktype/', views.Bhktype),
    path('bhktypeDelete/<int:bhktype_id>/', views.BhktypeDelete),
    path('floortype/', views.Floortype),
    path('floortypeDelete/<int:floortype_id>/', views.FloortypeDelete),
    path('tenenttype/', views.Tenenttype),
    path('tenenttypeDelete/<int:tenanttype_id>/', views.TenenttypeDelete),
    path('User/', views.User),
    path('UserDelete/<int:user_id>/', views.UserDelete),
    path('Owner/', views.Owner),
    path('OwnerDelete/<int:owner_id>/', views.OwnerDelete),
    path('House/', views.House),
    path("HouseUpdate/<int:house_id>/", views.HouseUpdate),
    path("HouseStatus/<int:house_id>/", views.HouseStatusUpdate),
    path('Gallery/', views.Gallery),
    path('UserGallery/', views.UserGallery),
    path('GalleryDelete/<int:gallery_id>/', views.GalleryDelete),
    path('Fav/', views.Fav),
    path('FavDelete/<int:favorite_id>/', views.FavDelete),
    path('UserBhktype/', views.UserBhktype),
    path('UserBhktypeDelete/<int:userbhktype_id>/', views.UserBhktypeDelete),
    path('UserFloortype/', views.UserFloortype),
    path('UserFloortypeDelete/<int:userfloortype_id>/', views.UserFloortypeDelete),
    path('Requested/', views.Requested),
    path('RequestedDelete/<int:requested_id>/', views.RequestedDelete),
    path('FixOldHouses/', views.FixOldHouses),
    path('AdvancePaymentUpdate/<int:request_id>/', views.AdvancePaymentUpdate), 
    
        path('Login/', views.Login),
        path('Userprofile/<int:id>/', views.Userprofile),
        path('OwnerProfile/<int:owner_id>/', views.OwnerProfile),
        path('UserUpdate/<int:user_id>/', views.editUserProfile),
        path('OwnerUpdate/<int:owner_id>/', views.editOwnerProfile),
        path('Userpassword/<int:uid>/', views.UserPassword),
        path('Ownerpassword/<int:oid>/', views.OwnerPassword),  
        path('OwnerRequestUpdate/<int:request_id>/', views.OwnerRequestUpdate),
        path('Complaint/', views.complaint),
        path('ComplaintDelete/<int:complaint_id>/', views.ComplaintDelete),
        path("ComplaintReply/<int:complaint_id>/", views.ComplaintReply),
        path('Feedback/', views.Feedback),
        path("AdminUserList/", views.AdminUserList),
        path("AdminUserStatus/<int:user_id>/", views.AdminUserStatusUpdate),
        path('AdminDashboardStats/', views.AdminDashboardStats),
        path("AdminOwnerList/", views.AdminOwnerList),
        path("AdminOwnerStatus/<int:owner_id>/", views.AdminOwnerStatusUpdate),
        path('OwnerChats/', views.OwnerChats),
        path("ChatMessages/", views.ChatHistory),
        path("DeleteChatRequest/<int:request_id>/", views.DeleteChatRequest),
        path("MarkSeen/<int:request_id>/", views.MarkSeen),
        path("UploadChatFile/", views.UploadChatFile),
        path("RecommendHouses/", views.RecommendHouses),
        path('DeleteChatMessage/<int:message_id>/', views.DeleteChatMessage),
        path('OwnerComplaint/', views.OwnerComplaint),
        path('AdminComplaint/', views.AdminComplaint),
        path("OwnerComplaintReply/<int:id>/", views.OwnerComplaintReply),
        path("SendOTP/",views.SendOTP),
        path("ResetPassword/",views.ResetPassword),


]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
