# Generated by Django 6.0.1 on 2026-01-24 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_tbl_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=50)),
                ('owner_email', models.CharField(max_length=50)),
                ('owner_password', models.CharField(max_length=50)),
                ('owner_photo', models.CharField(max_length=100)),
                ('owner_address', models.CharField(max_length=200)),
                ('owner_doj', models.CharField(max_length=20)),
                ('owner_status', models.CharField(max_length=20)),
                ('owner_proof', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_house',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_photo', models.CharField(max_length=100)),
                ('house_details', models.CharField(max_length=20)),
                ('house_price', models.CharField(max_length=300)),
                ('house_langtitude', models.CharField(max_length=50)),
                ('house_longtitude', models.CharField(max_length=50)),
                ('bhktype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_bhktype')),
                ('floortype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_floortype')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_place')),
                ('tenanttype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_tenenttype')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_owner')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery_file', models.CharField(max_length=100)),
                ('house_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_house')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_user')),
                ('house_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_house')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_requested',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_details', models.CharField(max_length=200)),
                ('requested_reply', models.CharField(max_length=200)),
                ('requested_status', models.CharField(max_length=20)),
                ('house_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_house')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_user')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_userbhktype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bhktype_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_bhktype')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_user')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_userfloortype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floortype_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_floortype')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_user')),
            ],
        ),
    ]
