# Generated by Django 6.0.1 on 2026-01-24 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_tbl_owner_tbl_house_tbl_gallery_tbl_favorite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_user',
            name='user_photo',
            field=models.FileField(upload_to='Assets/UserPhoto/'),
        ),
    ]
