# Generated by Django 6.0.1 on 2026-01-24 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_alter_tbl_user_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_house',
            name='house_photo',
            field=models.FileField(upload_to='Assets/HousePhoto/'),
        ),
        migrations.AlterField(
            model_name='tbl_owner',
            name='owner_photo',
            field=models.FileField(upload_to='Assets/OwnerPhoto/'),
        ),
        migrations.AlterField(
            model_name='tbl_owner',
            name='owner_proof',
            field=models.FileField(upload_to='Assets/OwnerProof/'),
        ),
    ]
