# Generated by Django 6.0.1 on 2026-01-24 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0007_alter_tbl_house_house_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_gallery',
            name='gallery_file',
            field=models.FileField(upload_to='Assets/Gallery/'),
        ),
    ]
