# Generated by Django 6.0.1 on 2026-01-29 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0008_alter_tbl_gallery_gallery_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_user',
            name='user_contact',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_user',
            name='user_photo',
            field=models.FileField(blank=True, null=True, upload_to='Assets/UserPhoto/'),
        ),
    ]
