# Generated by Django 6.0.1 on 2026-01-30 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0009_tbl_user_user_contact_alter_tbl_user_user_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_owner',
            name='owner_contact',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_owner',
            name='owner_address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tbl_owner',
            name='owner_doj',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_owner',
            name='owner_email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tbl_owner',
            name='owner_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tbl_owner',
            name='owner_password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tbl_owner',
            name='owner_photo',
            field=models.ImageField(blank=True, null=True, upload_to='owner_photo/'),
        ),
        migrations.AlterField(
            model_name='tbl_owner',
            name='owner_proof',
            field=models.ImageField(blank=True, null=True, upload_to='owner_proof/'),
        ),
        migrations.AlterField(
            model_name='tbl_owner',
            name='owner_status',
            field=models.IntegerField(default=1),
        ),
    ]
