# Generated by Django 6.0.1 on 2026-02-10 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0010_tbl_owner_owner_contact_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_gallery',
            name='house_id',
        ),
        migrations.RemoveField(
            model_name='tbl_requested',
            name='house_id',
        ),
        migrations.RemoveField(
            model_name='tbl_requested',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='tbl_user',
            name='tententtype',
        ),
        migrations.RemoveField(
            model_name='tbl_userbhktype',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='tbl_userfloortype',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='tbl_userbhktype',
            name='bhktype_id',
        ),
        migrations.RemoveField(
            model_name='tbl_userfloortype',
            name='floortype_id',
        ),
        migrations.DeleteModel(
            name='tbl_favorite',
        ),
        migrations.DeleteModel(
            name='tbl_gallery',
        ),
        migrations.DeleteModel(
            name='tbl_requested',
        ),
        migrations.DeleteModel(
            name='tbl_user',
        ),
        migrations.DeleteModel(
            name='tbl_userbhktype',
        ),
        migrations.DeleteModel(
            name='tbl_userfloortype',
        ),
    ]
