# Generated by Django 6.0.1 on 2026-02-10 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0011_remove_tbl_gallery_house_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery_file', models.FileField(upload_to='Assets/Gallery/')),
                ('house_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_house')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('user_email', models.CharField(max_length=50)),
                ('user_password', models.CharField(max_length=50)),
                ('user_photo', models.FileField(upload_to='Assets/UserPhoto/')),
                ('user_address', models.CharField(max_length=200)),
                ('user_dob', models.CharField(max_length=20)),
                ('user_contact', models.CharField(blank=True, max_length=15, null=True)),
                ('tententtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_tenenttype')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_requested',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_details', models.CharField(max_length=200)),
                ('requested_reply', models.CharField(max_length=200)),
                ('requested_status', models.CharField(max_length=20)),
                ('house_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_house')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_user')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_house')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_user')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_userbhktype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bhktype_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_bhktype')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_user')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_userfloortype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floortype_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_floortype')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_user')),
            ],
        ),
    ]
