# Generated by Django 6.0.1 on 2026-02-20 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0014_tbl_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_user',
            name='user_proof',
            field=models.FileField(blank=True, null=True, upload_to='Assets/UserProof/'),
        ),
        migrations.AlterField(
            model_name='tbl_user',
            name='user_photo',
            field=models.FileField(blank=True, null=True, upload_to='Assets/UserPhoto/'),
        ),
    ]
