# Generated by Django 6.0.1 on 2026-02-21 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0015_tbl_user_user_proof_alter_tbl_user_user_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_user',
            name='user_status',
            field=models.CharField(default='Active', max_length=20),
        ),
    ]
