# Generated by Django 6.0.1 on 2026-02-21 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0016_tbl_user_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_owner',
            name='owner_status',
            field=models.CharField(default='Active', max_length=20),
        ),
    ]
