# Generated by Django 6.0.1 on 2026-02-21 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0017_alter_tbl_owner_owner_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_house',
            name='house_status',
            field=models.CharField(default='Active', max_length=20),
        ),
    ]
