# Generated by Django 6.0.1 on 2026-03-03 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0018_tbl_house_house_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_house',
            name='house_price',
            field=models.IntegerField(),
        ),
    ]
