# Generated by Django 6.0.1 on 2026-03-03 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0019_alter_tbl_house_house_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_house',
            name='house_details',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tbl_house',
            name='house_langtitude',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_house',
            name='house_longtitude',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
