# Generated by Django 6.0.1 on 2026-03-03 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0020_alter_tbl_house_house_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_house',
            name='house_langtitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_house',
            name='house_longtitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
