# Generated by Django 6.0.1 on 2026-03-04 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0021_alter_tbl_house_house_langtitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_requested',
            name='advance_status',
            field=models.CharField(default='Not Paid', max_length=20),
        ),
    ]
