# Generated by Django 6.0.1 on 2026-03-04 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0022_tbl_requested_advance_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_requested',
            name='requested_amount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
