# Generated by Django 6.0.1 on 2026-03-04 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0023_tbl_requested_requested_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_rentpayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent_month', models.CharField(max_length=20)),
                ('rent_amount', models.IntegerField()),
                ('payment_status', models.CharField(default='Paid', max_length=20)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('house_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_house')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_user')),
            ],
        ),
    ]
