# Generated by Django 6.0.1 on 2026-03-10 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0024_tbl_rentpayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_id', models.IntegerField()),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_requested')),
            ],
        ),
        migrations.DeleteModel(
            name='tbl_category',
        ),
        migrations.AlterField(
            model_name='tbl_admin',
            name='admin_password',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tbl_owner',
            name='owner_password',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tbl_user',
            name='user_password',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='tbl_rentpayment',
        ),
    ]
