# Generated by Django 6.0.1 on 2026-03-10 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0025_chat_delete_tbl_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='sender',
            field=models.CharField(default='user', max_length=20),
            preserve_default=False,
        ),
    ]
