# Generated by Django 6.0.1 on 2026-03-12 14:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0027_remove_chat_request_chat_file_chat_is_seen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_requested',
            name='requested_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
