# Generated by Django 6.0.1 on 2026-03-13 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0028_tbl_requested_requested_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_owner_complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_title', models.CharField(max_length=100)),
                ('complaint_details', models.CharField(max_length=200)),
                ('complaint_reply', models.CharField(default='', max_length=200)),
                ('complaint_status', models.CharField(default='Pending', max_length=20)),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_owner')),
            ],
        ),
    ]
